### PR TITLE
Create new setting option

### PR DESCRIPTION
**Pull request by borisbauer-unity**
### Description

Added an option on the first welcome layout of PA.

### Changes made

- ProjectAuditorWindow has a new "Create New Settings" button with a layout on the right of the settings drop-down
- the "Create New Settings" button action uses the standard save file prompt, saves a new ProjectSettings asset if the requester was not cancelled
- creating a new settings asset selects this asset both as the current PA setting and as the current selected asset in the Editor, i.e. the Inspector (if open/visible) shows the settings right away to the user

### Notes

TODO: I could update the docs regarding the settings in this PR, unless we prefer a full pass over the docs at a later time.

### CODE REVIEW

**Comment by borisbauer-unity** [comment]
I found a much better alternative API for new/save file prompts:

A different Unity UI method `EditorUtility.SaveFilePanelInProject()` ensures that a user only picks a path within Assets.

Note:  This API is not fully documented. It features an optional relative path parameter AND guarantees a returned relative path (relative to Assets/), both in their UX warning the user and what the returned string contains.

**Comment by mtrive** [comment]
found a little bug:
- Create a New Settings Asset
- Change selection to Default
- Click on the dropdown list

The new settings asset does not appear on the list

**Comment by borisbauer-unity** [comment]
> The new settings asset does not appear on the list

Oh, right, there was not a general refresh so far for that drop-down interaction and at creation time.

Maybe I should add it even for the drop-down action, so it would detect any new asset on disk.

**Review by mtrive — APPROVED** [review]
Nice!

**Pull request merged**
