### PR TITLE
Compiler Messages View

### PR DESCRIPTION
**Pull request by mtrive**
**Problem**
Any compilation error causes the analysis to fail. This is not a great user experience since you might still want to review non-code relates issues and information (see https://github.com/Unity-Technologies/ProjectAuditor/issues/34)

**Solution**
With this PR, it is possible to look at the report and navigate through all views even in the event of a compilation error.
If there is indeed an error, this is clearly reported in the summary view:

summary-compiler-errors

Then, the errors are reported in the C# compiler messages view:.

compiler-messages-view

Like other code-related issues, double-clicking on a compiler message will take the user to the script in the default IDE. Note that the compiler messages won't change after editing a C# file. To update the view, the user needs to re-run the analysis, like for any other view.

Note that there are 3 ways open the C# compiler messages view.
1. View menu in the toolbar
2. Summary view shortcut
3. Code Diagnostics view shortcut

Finally, the Code view shows a message to inform the user that the code analysis is incomplete:

code-view-compiler-errors

### CODE REVIEW

**Review by unitystevem — CHANGES_REQUESTED** [review]
Some issues here, I’m afraid…

1) Console window prints what looks like an error (although it’s just a log) when opening the Compiler messages view:

SendUIButtonEvent: Unsupported button type : CodeCompilerMessages
UnityEngine.Debug:LogFormat (string,object[])
Unity.ProjectAuditor.Editor.UI.ProjectAuditorAnalytics:GetButtonName (Unity.ProjectAuditor.Editor.UI.ProjectAuditorAnalytics/UIButton) (at Library/PackageCache/com.unity.project-auditor@1a077005c8/Editor/UI/ProjectAuditorAnalytics.cs:190)
Unity.ProjectAuditor.Editor.UI.ProjectAuditorAnalytics:SendUIButtonEvent (Unity.ProjectAuditor.Editor.UI.ProjectAuditorAnalytics/UIButton,Unity.ProjectAuditor.Editor.UI.ProjectAuditorAnalytics/Analytic) (at Library/PackageCache/com.unity.project-auditor@1a077005c8/Editor/UI/ProjectAuditorAnalytics.cs:312)
Unity.ProjectAuditor.Editor.UI.ProjectAuditorWindow:OnViewChanged (object) (at Library/PackageCache/com.unity.project-auditor@1a077005c8/Editor/UI/ProjectAuditorWindow.cs:586)
UnityEditor.GenericMenu:CatchMenu (object,string[],int) (at /Users/bokken/buildslave/unity/build/Editor/Mono/GUI/GenericMenu.cs:124)

2) My biggest problem is that I don’t know how to reproduce the kind of problem you’re trying to solve with this feature. If I just add a compile error into a user script (for example by just typing nonsense into a file), the Summary view shows no compilation errors, and the Code Diagnostics and C# Messages windows show “No issues”. 

3) I had some compiler warnings in a package. The Source column contained the full path (/users/me/a/bunch/of/subfolders/Project/Library/PackageCache/com.unity.blah/Editor/Foo/Foo.cs) which made it far too long to view on a single line. The Message column contained the full path again before the actual compiler warning, making it even longer. We need a better way to display this. Perhaps when you click on an issue there should be a couple of boxes at the bottom of the window, full width, with text wrapping, that show the path and message?

4) I’d like to see a different tree view layout to make it easier to examine issues:

First, the Compiler error/warning code (e.g. CS1234). These should act like our Issue column in the Code Diagnostics view - initially collapsed with a number in bracket indicating the number of instances. This will let users ignore frequent, harmless warnings (e.g. unused variables) but expand the serious-looking ones to investigate further.

Second column: An icon to indicate whether this is a warning or an error.

Third column: The actual warning/error message

Fourth column (revealed by expanding an error/warning): File:line

Fifth column (revealed by expanding an error/warning): Assembly

Sixth column (revealed by expanding an error/warning): Full file path

**Comment by mtrive** [comment]
@unitystevem Great feedback.

> 1. Console window prints what looks like an error (although it’s just a log) when opening the Compiler messages view:
> 
> SendUIButtonEvent: Unsupported button type : CodeCompilerMessages

Fixed.

> 2. My biggest problem is that I don’t know how to reproduce the kind of problem you’re trying to solve with this feature. If I just add a compile error into a user script (for example by just typing nonsense into a file), the Summary view shows no compilation errors, and the Code Diagnostics and C# Messages windows show “No issues”.

This is due to the API used to compile the assemblies, if there is an error in Editor code it will just fail with no messages.
My test case had an error in non-editor code, that's why I did not run into. To be honest, I did experience what you are seeing but I overlooked it.

To fix it I reimplemented the assembly compilation pipeline on top of [AssemblyBuilder](https://docs.unity3d.com/ScriptReference/Compilation.AssemblyBuilder.html) instead of the previous [PlayerBuildInterface.CompilePlayerScripts](https://docs.unity3d.com/ScriptReference/Build.Player.PlayerBuildInterface.CompilePlayerScripts.html) (horrible API). It seems to work fine but of course it needs some testing.

> 3. I had some compiler warnings in a package. The Source column contained the full path (/users/me/a/bunch/of/subfolders/Project/Library/PackageCache/com.unity.blah/Editor/Foo/Foo.cs) which made it far too long to view on a single line. The Message column contained the full path again before the actual compiler warning, making it even longer. We need a better way to display this. Perhaps when you click on an issue there should be a couple of boxes at the bottom of the window, full width, with text wrapping, that show the path and message?
> 3. I’d like to see a different tree view layout to make it easier to examine issues:
> 
> First, the Compiler error/warning code (e.g. CS1234). These should act like our Issue column in the Code Diagnostics view - initially collapsed with a number in bracket indicating the number of instances. This will let users ignore frequent, harmless warnings (e.g. unused variables) but expand the serious-looking ones to investigate further.
> ...

Fixed.

Let me know if I missed anything. Thanks!

**Comment by unitystevem** [comment]
Still some issues, I'm afraid. I've attached a screenshot of a project where I deliberately introduced a compile error in an Editor script (the same thing happens in a player script). The console window (bottom of the screenshot) shows a couple of compile errors, and the Project Auditor shows 11 completely different compile errors. The formatting is broken on some errors (looks like it's trying to render 2+ lines of text in the space of a single line). 

In addition, whilst the tree view for compiler messages is an improvement (except for the formatting issue described above), it would be better to have the the warning/error icons in the display alongside the message codes. Otherwise, when all the roots are collapsed, it's not possible to see which codes related to warnings and which are errors. You end up having to expand them all one by one.

Happy to supply my repro project for this. Message me on Slack and I'll send over a zip file if it's useful.

Screenshot 2021-04-21 at 20 59 41
Screenshot 2021-04-21 at 21 05 56

**Comment by mtrive** [comment]
> Still some issues, I'm afraid. I've attached a screenshot of a project where I deliberately introduced a compile error in an Editor script (the same thing happens in a player script). The console window (bottom of the screenshot) shows a couple of compile errors, and the Project Auditor shows 11 completely different compile errors. The formatting is broken on some errors (looks like it's trying to render 2+ lines of text in the space of a single line).

The extra errors were due to some Assemblies that could not be compiled because of missing dependencies. This is fixed. It seems the text problem was related the extra long errors because I can't repro anymore. I'll keep testing and keep an eye on it.


> In addition, whilst the tree view for compiler messages is an improvement (except for the formatting issue described above), it would be better to have the the warning/error icons in the display alongside the message codes. Otherwise, when all the roots are collapsed, it's not possible to see which codes related to warnings and which are errors. You end up having to expand them all one by one.

Done
message-icon

**Review by unitystevem — APPROVED** [review]
This is looking and working well now.

**Pull request merged**
