### PR TITLE
Shaders View and Shader Variant Window

### PR DESCRIPTION
**Pull request by mtrive**
This is an iteration over the previous shader auditing PR: https://github.com/Unity-Technologies/ProjectAuditor/pull/2.

This PR moves the existing shader variants to their own Editor Window, which can be enabled if the user clicks on the "Inspect Shader Variants" button. By default, Shaders mode reports all shaders in the project and their:
- Total number of variants
- Number of passes
- Num Keywords
- Render Queue
- Instancing enabled/disabled

Note that the Shader Variants window can be docked like any other window.
shader-variant-window

### CODE REVIEW

**Review by unitystevem — CHANGES_REQUESTED** [review]
A number of bugs with this that would be good to get fixed before a merge:

1 - Having done a build before installing/running the Project Auditor (but without closing the Unity Editor), the Shader Variants window told me I had to do another build

2 - When I did a build, the Shader Variants window still didn’t refresh. I had to click Analyse again. Could there be some automated way for Project Auditor to run the analysis that relies on build report data automatically when a build gets completed (assuming the Project Auditor window is open)?

3 - The first column in the Shader Variants window (and the Shaders tab) is titled “Issue” should be called “Shader”, or something.

4 - In the project I tested with, one of the shaders with the highest listed “Total Variants” didn’t appear in the Shader Variants window at all after building. I suspect it’s because the shader isn’t actually used in the project and gets stripped out of the build, but Project Auditor doesn’t have any way to explain or confirm that. Could the variants window include information on shaders that have no variants in the actual build? Or better yet, a column in the Shaders tab showing “Actual Variants” that gets populated after the build. Then I could easily see “MyShaders/CustomVertexColor Total: 24582 Actual: 0” and immediately see it’s getting removed from the build completely.

5 - Right-clicking the Shader Variant tab and selecting Maximise causes the tab to close and shows the following error in the console:

NullReferenceException: Object reference not set to an instance of an object
UnityEditor.WindowLayout.MaximizePresent (UnityEditor.EditorWindow win) (at /Users/bokken/buildslave/unity/build/Editor/Mono/GUI/WindowLayout.cs:655)
UnityEditor.WindowLayout.Maximize (UnityEditor.EditorWindow win) (at /Users/bokken/buildslave/unity/build/Editor/Mono/GUI/WindowLayout.cs:585)
UnityEditor.DockArea.Maximize (System.Object userData) (at /Users/bokken/buildslave/unity/build/Editor/Mono/GUI/DockArea.cs:640)
UnityEditor.GenericMenu.CatchMenu (System.Object userData, System.String[] options, System.Int32 selected) (at /Users/bokken/buildslave/unity/build/Editor/Mono/GUI/GenericMenu.cs:119)

6 - Seemingly repeated variants. For instance, in this project “Hidden/Universal Render Pipeline/CameraMotionBlue” shows 6 variants: 3 each for Metal and OpenGLCore, none of them showing any keywords. It’s as if something other than the platform and the keywords is creating additional variants, but Project Auditor isn’t showing what the cause is.

**Comment by mtrive** [comment]
Thanks for your feedback Steve!

1 - Unfortunately, for Project Auditor be be aware of builds, it needs to be installed before building.
2 - I agree it's not optimal. It might be tricky to fix but I will take a look
3 - Fixed in https://github.com/Unity-Technologies/ProjectAuditor/pull/3/commits/3622c7477c5196dace9f2689c7e6bf785db69440
4 - Need to investigate
5 - That seems to work for me. Was it on Windows?  
6 - Need to investigate

**Comment by unitystevem** [comment]
1 - Fair enough. It's not a showstopper in and of itself, but not refreshing once a build has been done is definitely annoying/confusing.

2 - See 1... Could something like this help? https://docs.unity3d.com/ScriptReference/Callbacks.PostProcessBuildAttribute.html ... Minimum Viable Product here is that if the Project Auditor window is open, just call Analyze again in the callback.

3 - Nice :)

4 - Can send the project if you like. It's a reasonably small customer test project which I just happened to have open

5 - Nope, on Mac. 2019.4.15f1. Happens 100% for me

6 - Again, can share the project if it's useful

**Comment by mtrive** [comment]
I think I addressed all your points with the exception of 1 and 6. It should be in a good shape for landing to _master_ but let me know what you think.

**Comment by unitystevem** [comment]
Sorry to be a pain with this one, but there are still a few issues here :(

5 - Issue 5 (Shader Variant window produces error and disappears if you right click on the tab and try to Maximise it) is not fixed for me. Same error as I was seeing before. 

Everything else from the original list of issues (except 1, which is fine) seems fixed, but I spotted a few new ones... Continuing the numbering scheme...

7 - Trying to sort Shader Variants by the Pass Name results in errors. I think you need to change the Format for the column to a PropertyFormat.String. It's an integer right now:

NullReferenceException: Object reference not set to an instance of an object
Unity.ProjectAuditor.Editor.UI.IssueTable+ItemTree+<>c__DisplayClass7_0.<Sort>b__0 (Unity.ProjectAuditor.Editor.UI.IssueTable+ItemTree a, Unity.ProjectAuditor.Editor.UI.IssueTable+ItemTree b) (at Library/PackageCache/com.unity.project-auditor@6e4b7c2238/Editor/UI/IssueTable.cs:515)

8 - Shaders in the Shader Variants window don’t appear to initially be sorted in any particular order. You have to click the Shader Name column to sort them.

9 - It would be nice to be able to click on a shader in the Project Auditor window and have that shader be automatically selected in the Shader Variant window. This one is a bit more wish-list/quality of life than an actual bug, admittedly.

**Comment by mtrive** [comment]
Thanks Steve!
5 - Fixed by eb95712.
7 - Fixed by 263caf2
8 - Both Shaders and Variants are now sorted alphabetically in 2f66918
9 - I agree. I'll implement that separately.

**Review by unitystevem — APPROVED** [review]
Looking really good now! Auto-alphabetical sorting and the ability to maximise the variants window has made a HUGE difference to how usable this feels

**Comment by mtrive** [comment]
Thanks for your feedback. It is indeed much better now.

**Pull request merged**
