### PR TITLE
Add Unity Version check on descriptors

### PR DESCRIPTION
**Pull request by mtrive**
**Problem**
Some potential issues should not be reported on specific versions of Unity. For example, [Camera.main](https://docs.unity3d.com/ScriptReference/Camera-main.html) which is known to have a CPU cost, has been optimized recently in 2020.x and the fix has been backported to 2019.4.9. Therefore, it should only be reported up to 2019.4.8. Similarly, some issues should only be reported from a specific version, for example in relation to a new API such as [PlayerSettings.mipStripping](https://docs.unity3d.com/2020.1/Documentation/ScriptReference/PlayerSettings-mipStripping.html) which was added in 2020.1

**Solution**
Add _minimumVersion_ and _maximumVersion_ properties to _ProblemDescriptors_ so that they can be checked against the Unity Editor version.

Note that the version check is only performed starting 2019.x

@lyndon-unity (for awareness)

### CODE REVIEW

**Comment by lyndon-unity** [comment]
Great to see, thanks for looping me onto this.

**Review by unitystevem — COMMENTED** [review]
ApiDatabase.json : there’s a rogue space in the maximumVersion string

ProblemDescriptor.cs - Constructor maintenance looks error prone. Could you keep the new constructor and change the original one to something like this? :

public ProblemDescriptor(int id, string description, Area area) : this(id, description, area.ToString())
{
}

In general I think this is a good addition but I'm trying to imagine how it works in practice. Let's say some problem was introduced in 2018.1.0f and eventually gets fixed in trunk in 2020.2.4f1, which then gets backported to 2019.4.21f1. That problem still exists in Unity versions between 2018.1.0 and 2019.4.20, but it ALSO still exists between 2020.1.0f and 2020.2.3f1. Do we have to create two separate issues for this, one for the 2018/2019 versions and one for 2020?

**Comment by mtrive** [comment]
> there’s a rogue space in the maximumVersion string

fixed. In addition, I improved backwards compatibility and added tests coverage.

> 
> ProblemDescriptor.cs - Constructor maintenance looks error prone. Could you keep the new constructor and change the original one to something like this? :
> 
> public ProblemDescriptor(int id, string description, Area area) : this(id, description, area.ToString())
> {
> }
> 

Good feedback. I consolidated the constructors.

> In general I think this is a good addition but I'm trying to imagine how it works in practice. Let's say some problem was introduced in 2018.1.0f and eventually gets fixed in trunk in 2020.2.4f1, which then gets backported to 2019.4.21f1. That problem still exists in Unity versions between 2018.1.0 and 2019.4.20, but it ALSO still exists between 2020.1.0f and 2020.2.3f1. Do we have to create two separate issues for this, one for the 2018/2019 versions and one for 2020?

I think this is a possibility and, yes, that would be a workaround. This solution meets the requirements of Camera.main and PlayerSettings.mipStripping, however, if we find that we need more flexibility it's something we can revisit in the future. How does that sound?

**Comment by unitystevem** [comment]
Fair enough. Better not to get bogged down in hypothetical situations now, and to focus on the problems we actually encounter :)

**Review by unitystevem — APPROVED** [review]

**Pull request merged**
