### PR TITLE
Report an issue if the splash screen is enabled and can be disabled

### PR DESCRIPTION
**Pull request by mtrive**
**Problem**
The Splash Screen can easily add 2+ seconds (depending on platform/project) to the total loading time into the first scene from launch. 

**Solution**
Report if the Splash Screen option is enabled when using paid-versions of Unity.

Note that the Unity Splash Screen cannot be disabled on free versions of Unity. It can, otherwise, be disabled.

### CODE REVIEW

**Review by unitystevem — COMMENTED** [review]
Is there some reason why this issue has different data/rules to all the others that I haven't understood?

ProjectSettings.json
- new issue is 201030 (there apparently isn’t a 201029?)
- type should be "UnityEditor.PlayerSettings.SplashScreen" : there is no “UnityEngine.PlayerSettings” AFAIK, and the type field doesn’t usually include the property/method
- area should be “Load Times”

SettingsAuditor.cs
- What’s “UnityEngine.PlayerSettings”? I didn’t think such a class existed. There’s already an entry for “UnityEditor.PlayerSettings”
- Change to line 105 shouldn't be necessary if the data is correct

**Comment by mtrive** [comment]
> Is there some reason why this issue has different data/rules to all the others that I haven't understood?
> 
> ProjectSettings.json
> 
> * new issue is 201030 (there apparently isn’t a 201029?)
> * type should be "UnityEditor.PlayerSettings.SplashScreen" : there is no “UnityEngine.PlayerSettings” AFAIK, and the type field doesn’t usually include the property/method
> * area should be “Load Times”
> 
> SettingsAuditor.cs
> 
> * What’s “UnityEngine.PlayerSettings”? I didn’t think such a class existed. There’s already an entry for “UnityEditor.PlayerSettings”
> * Change to line 105 shouldn't be necessary if the data is correct

Yes:
- Id should definitely be 201029
- Type should be "UnityEditor.PlayerSettings.SplashScreen"

_UnityEngine.PlayerSettings_ is the runtime "counterpart" of _UnityEditor.PlayerSettings_. See [PlayerSettings.SplashScreen](https://docs.unity3d.com/ScriptReference/PlayerSettings.SplashScreen.htm).

On the “LoadTimes” instead of “Load Times”: at some point I had to remove all spaces from area names. This might make the current json database inconsistent with the _source_ spreadsheet. Having said that, I would not go ahead and fix that yet as it is likely to change again. 

Does this answer your questions?

**Review by unitystevem — APPROVED** [review]
I'm still confused about why Project Auditor would want to check UnityEngine.PlayerSettings.SplashScreen rather than UnityEditor.PlayerSettings.SplashScreen... But if you're certain that this is necessary and preferable, I trust you :) I tested it and it seems to work fine.

**Comment by mtrive** [comment]
@unitystevem You were right to be suspicious of the namespace. It's fixed now.

**Review by unitystevem — APPROVED** [review]

**Pull request merged**
